/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chniccs_security_JniUtil */

#ifndef _Included_com_chniccs_security_JniUtil
#define _Included_com_chniccs_security_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chniccs_security_JniUtil
 * Method:    getKeyStorePW
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chniccs_security_JniUtil_getKeyStorePW
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_chniccs_security_JniUtil
 * Method:    getAESkey
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chniccs_security_JniUtil_getAESkey
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
